# Optimized Tagging Configuration Example
# This configuration demonstrates high-performance tagging with memory management

# Memory store for optimized tagging
memory:
  max_size: 50000
  max_memory_mb: 500
  default_ttl: 10m
  cleanup_interval: 30s
  eviction_policy: lru
  enable_stats: true

# General cache settings
default_ttl: 10m
max_retries: 3
retry_delay: 100ms
codec: json

# Optimized tagging settings for high-throughput
optimized_tagging:
  enable_persistence: true
  tag_mapping_ttl: 24h
  batch_size: 500
  enable_stats: true
  load_timeout: 5s
  enable_background_persistence: true
  persistence_interval: 30s
  enable_memory_optimization: true
  max_memory_usage: 524288000  # 500MB
  batch_flush_interval: 2s

# Observability settings
observability:
  enable_metrics: true
  enable_tracing: true
  enable_logging: true
  service_name: "cachex-optimized-tagging"
  service_version: "1.0.0"
  environment: "production"
  log_level: "info"
  metrics_interval: 30s
  trace_sampling_rate: 0.1

# Memory pool settings for high performance
memory_pool:
  enabled: true
  initial_size: 500
  max_size: 5000
  cleanup_interval: 2m
  enable_stats: true

# Allocation optimization for high throughput
allocation_optimization:
  enabled: true
  enable_memory_pools: true
  enable_buffer_pooling: true
  enable_string_optimization: true
  enable_map_optimization: true
  enable_value_copy_optimization: true

# Validation cache for performance
validation_cache:
  enabled: true
  ttl: 1h
  max_size: 2000
  enable_stats: true
  cleanup_interval: 5m
