# Optimized Connection Pool Configuration Example
# This configuration demonstrates high-performance Redis connection pooling

optimized_connection_pool:
  # Redis connection settings
  addr: "localhost:6379"
  password: ""
  db: 0
  
  # TLS configuration
  tls:
    enabled: false
    insecure_skip_verify: false
  
  # Advanced connection pool settings
  pool_size: 50
  min_idle_conns: 20
  max_retries: 5
  pool_timeout: 30s
  idle_timeout: 5m
  idle_check_frequency: 1m
  
  # Timeout settings
  dial_timeout: 5s
  read_timeout: 1s
  write_timeout: 1s
  
  # Performance settings
  enable_pipelining: true
  enable_metrics: true
  enable_connection_pool: true
  
  # Health check settings
  health_check_interval: 15s
  health_check_timeout: 2s
  
  # Connection pool optimization settings
  enable_connection_reuse: true
  enable_connection_warming: true
  connection_warming_timeout: 30s
  enable_load_balancing: true
  enable_circuit_breaker: true
  
  # Monitoring settings
  enable_pool_monitoring: true
  monitoring_interval: 1m

# General cache settings
default_ttl: 10m
max_retries: 5
retry_delay: 50ms
codec: msgpack

# Observability settings
observability:
  enable_metrics: true
  enable_tracing: true
  enable_logging: true
  service_name: "cachex-optimized-pool"
  service_version: "1.0.0"
  environment: "production"
  log_level: "info"
  metrics_interval: 15s
  trace_sampling_rate: 0.2

# Memory pool settings for high performance
memory_pool:
  enabled: true
  initial_size: 200
  max_size: 2000
  cleanup_interval: 2m
  enable_stats: true

# Allocation optimization for high throughput
allocation_optimization:
  enabled: true
  enable_memory_pools: true
  enable_buffer_pooling: true
  enable_string_optimization: true
  enable_map_optimization: true
  enable_value_copy_optimization: true

# Validation cache for performance
validation_cache:
  enabled: true
  ttl: 30m
  max_size: 2000
  enable_stats: true
  cleanup_interval: 2m
