# Ristretto Store Configuration Example
ristretto:
  max_items: 10000
  max_memory_bytes: 104857600  # 100MB
  default_ttl: 5m
  num_counters: 100000
  buffer_items: 64
  enable_metrics: true
  enable_stats: true
  batch_size: 10

# General cache settings
default_ttl: 5m
max_retries: 3
retry_delay: 100ms

# Codec settings
codec: json

# Observability settings
observability:
  enable_metrics: true
  enable_tracing: true
  enable_logging: true
  service_name: "cachex-ristretto"
  service_version: "1.0.0"
  environment: "production"
  log_level: "info"
  metrics_interval: 30s
  trace_sampling_rate: 0.1

# Security settings
security:
  validation:
    max_key_length: 256
    max_value_size: 1048576  # 1MB
    blocked_patterns:
      - "^\.\./"
      - "[<>\"'&]"
      - "javascript:"
      - "data:text/html"
  redaction_patterns:
    - '"password"\s*:\s*"[^"]*"'
    - '"token"\s*:\s*"[^"]*"'
    - '"key"\s*:\s*"[^"]*"'
    - '"secret"\s*:\s*"[^"]*"'
  redaction_replacement: "[REDACTED]"
  secrets_prefix: "VAULT_"

# Tagging settings
tagging:
  enable_persistence: true
  tag_mapping_ttl: 24h
  batch_size: 100
  enable_stats: true
  load_timeout: 5s

# Optimized tagging settings (for high-throughput)
optimized_tagging:
  enable_persistence: true
  tag_mapping_ttl: 24h
  batch_size: 200
  enable_stats: true
  load_timeout: 5s
  enable_background_persistence: true
  persistence_interval: 30s
  enable_memory_optimization: true
  max_memory_usage: 209715200  # 200MB
  batch_flush_interval: 5s

# Refresh ahead settings
refresh_ahead:
  enabled: true
  refresh_interval: 30s
  default_refresh_before: 2m
  max_concurrent_refreshes: 10
  enable_distributed_lock: true
  lock_timeout: 30s
  enable_metrics: false
  default_ttl: 5m
  unlock_timeout: 30s
  max_consecutive_failures: 3
  max_task_age: 1h

# GORM integration settings
gorm:
  enable_invalidation: true
  enable_read_through: true
  default_ttl: 5m
  enable_query_cache: true
  key_prefix: "gorm"
  enable_debug: false
  batch_size: 100

# Memory pool settings
memory_pool:
  enabled: true
  initial_size: 100
  max_size: 1000
  cleanup_interval: 5m
  enable_stats: true

# Allocation optimization settings
allocation_optimization:
  enabled: true
  enable_memory_pools: true
  enable_buffer_pooling: true
  enable_string_optimization: true
  enable_map_optimization: true
  enable_value_copy_optimization: true

# Validation cache settings
validation_cache:
  enabled: true
  ttl: 1h
  max_size: 1000
  enable_stats: true
  cleanup_interval: 5m
