# Simple Memory Store Configuration Example
memory:
  max_size: 10000
  max_memory_mb: 100
  default_ttl: 5m
  cleanup_interval: 1m
  eviction_policy: lru
  enable_stats: true

# General cache settings
default_ttl: 5m
max_retries: 3
retry_delay: 100ms

# Codec settings
codec: json

# Observability settings
observability:
  enable_metrics: true
  enable_tracing: true
  enable_logging: true
